version: 2
registries:
  spring-commercial:
    type: maven-repository
    url: https://repo.spring.io/artifactory/spring-commercial-release-remote-cache
    username: ${{ secrets.ARTIFACTORY_RO_USERNAME }}
    password: ${{ secrets.ARTIFACTORY_RO_PASSWORD }}

updates:

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    registries:
      - spring-commercial
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
    labels:
      - 'type: dependency-upgrade'
    groups:
      development-dependencies:
        update-types:
          - patch
        patterns:
          - com.gradle.enterprise
          - com.github.spotbugs
          - io.spring.*
          - org.ajoberstar.grgit
          - org.antora
          - io.micrometer:micrometer-docs-generator
          - com.willowtreeapps.assertk:assertk-jvm
          - org.hibernate.validator:hibernate-validator
          - org.apache.httpcomponents.client5:httpclient5
          - org.awaitility:awaitility
          - org.xerial.snappy:snappy-java
          - org.lz4:lz4-java
          - com.github.luben:zstd-jni

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'type: task'
    groups:
      development-dependencies:
        patterns:
          - '*'
