name: CI SNAPSHOT

on:
  workflow_dispatch:

  push:
    branches:
      - '*.x'

concurrency:
  group: group-snapshot-for-${{ github.ref }}
  cancel-in-progress: true

env:
  ARTIFACTORY_URL: ${{ secrets.COMMERCIAL_ARTIFACTORY_URL }}

jobs:
  build-snapshot:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-artifactory-gradle-snapshot.yml@main
    with:
      artifactoryUrl: ${{ env.ARTIFACTORY_URL }}
      targetRepository: spring-enterprise-maven-dev-local
      artifactoryProjectKey: spring
      runner: ubuntu22-2-8
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}
