name: Verify Staged Artifacts

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version like 5.0.0-M1, 5.1.0-RC1, 5.2.0 etc.'
        required: true
        type: string

env:
  ARTIFACTORY_USERNAME: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}

jobs:
  verify-staged-with-samples:
    runs-on: ubuntu22-2-8
    steps:

      - name: Checkout Samples Repo
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-integration-commercial
          ref: 6.1.x
          show-progress: false

      - name: Set up Gradle
        uses: spring-io/spring-gradle-build-action@v2

      - name: Prepare Spring Integration project against Staging
        run: |
          printf "allprojects {
                  repositories {
                    maven { 
                      url 'https://usw1.packages.broadcom.com/artifactory/spring-enterprise-maven-stage-local'
                      credentials {
                        username = '$ARTIFACTORY_USERNAME'
                        password = '$ARTIFACTORY_PASSWORD'
                      }
                    }
                  }
                }" > staging-repo-init.gradle
          
          sed -i "1,/springAmqpVersion.*/s/springAmqpVersion.*/springAmqpVersion='${{ inputs.releaseVersion }}'/" build.gradle  

      - name: Verify Spring Integration AMQP module against staged release
        run: gradle :spring-integration-amqp:check --init-script staging-repo-init.gradle